DOMAIN_DESCRIPTIONS = { 
        "customer_data_platform_analytics": {
            "schema": "public",
            "table": "cdp_ef",
            "columns": {
                "churn_risk_score": "Score de risco de churn do cliente.",
                "cliente": "Nome do cliente.",
                "downsell": "Valor de downsell realizado.",
                "downsell_m_0_3_mean": "Média de downsell nos últimos 3 meses.",
                "downsell_score": "Score de downsell.",
                "facebook_spend": "Gasto total em tráfego no Facebook.",
                "fase_atual": "Fase atual do projeto.",
                "franqueado": "Nome do franqueado.",
                "google_spend": "Gasto total em tráfego no Google",
                "id_cliente": "Identificador único do cliente.",
                "id_franqueado": "Identificador único do franqueado.",
                "id_projeto": "Identificador único do projeto.",
                "investimento": "Valor total investido.",
                "investimento_m_0_3_mean": "Média de investimento nos últimos 3 meses.",
                "investment_score": "Score de investimento.",
                "is_churn": "Indicador se o cliente está em churn (1 para sim, 0 para não).",
                "lifetime_months": "Tempo de vida do cliente em meses.",
                "margem_contribuicao": "Margem de contribuição do cliente.",
                "mhs": "MHS do cliente.",
                "mhs_m_0_3_mean": "Média de MHS nos últimos 3 meses.",
                "mhs_score": "Score de MHS.",
                "nps": "NPS do cliente.",
                "nps_m_0_3_mean": "Média de NPS nos últimos 3 meses.",
                "nps_score": "Score de NPS.",
                "observation_period": "Período de observação dos dados.",
                "ratio_receita_custo": "Razão entre receita e custo.",
                "receita": "Receita total do cliente.",
                "receita_custo_score": "Score de receita/custo.",
                "roas": "ROAS do cliente.",
                "roas_m_0_3_mean": "Média de ROAS nos últimos 3 meses.",
                "roas_score": "Score de ROAS.",
                "roi": "ROI do cliente.",
                "upsell": "Valor de upsell realizado.",
                "vlr_corretagem": "Valor de corretagem.",
                "vlr_deal": "Valor do deal.",
                "vlr_deal_atual": "Valor atual do deal.",
                "vlr_downsell": "Valor de downsell.",
                "vlr_revenue_share": "Valor de revenue share.",
                "vlr_servico_extra": "Valor de serviço extra.",
                "vlr_upsell": "Valor de upsell.",
                "escopo_projeto": "Escopo do projeto.",
                "inserted_at": "Data e hora em que os dados foram inseridos."
            }
        },
        "public": {
        "schema": "public",
        "table": "bank_fraud",
        "columns": {
            "customer_id": "Um identificador único para cada cliente dentro do sistema do banco.",
            "customer_name": "O nome do consumidor que está realizando a transação.",
            "gender": "O gênero do consumidor (por exemplo, Masculino, Feminino, Outro).",
            "age": "A idade do consumidor no momento da transação.",
            "state": "O estado em que o cliente reside.",
            "city": "A cidade onde o cliente reside.",
            "bank_branch": "A agência bancária específica onde o cliente possui sua conta.",
            "account_type": "O tipo de conta mantida pelo cliente (por exemplo, Poupança, Corrente).",
            "transaction_id": "Um identificador único para cada transação.",
            "transaction_date": "A data em que a transação ocorreu.",
            "transaction_time": "O horário específico em que a transação foi iniciada.",
            "transaction_amount": "O valor monetário da transação.",
            "merchant_id": "Um identificador único para o comerciante envolvido na transação.",
            "transaction_type": "A natureza da transação (por exemplo, Saque, Depósito, Transferência).",
            "merchant_category": "A categoria do comerciante (por exemplo, Varejo, Online, Viagem).",
            "account_balance": "O saldo da conta do cliente após a transação.",
            "transaction_device": "O dispositivo utilizado pelo cliente para realizar a transação (por exemplo, Móvel, Desktop).",
            "transaction_location": "A localização geográfica (por exemplo, latitude, longitude) da transação.",
            "device_type": "O tipo de dispositivo usado para a transação (por exemplo, Smartphone, Laptop).",
            "is_fraud": "Um indicador binário (1 ou 0) indicando se a transação é fraudulenta ou não.",
            "transaction_currency": "A moeda utilizada para a transação (por exemplo, USD, EUR).",
            "customer_contact": "O número de contato do cliente.",
            "transaction_description": "Uma breve descrição da transação (por exemplo, compra, transferência).",
            "customer_email": "O endereço de e-mail associado à conta do cliente.",
            "inserted_at": "Data de inserção dos dados."
        }
    }
}


