DOMAIN_DESCRIPTIONS = { 
        "customer_data_platform_analytics": {
            "schema": "public",
            "table": "cdp_ef",
            "columns": {
                "churn_risk_score": "Score de risco de churn do cliente.",
                "cliente": "Nome do cliente.",
                "downsell": "Valor de downsell realizado.",
                "downsell_m_0_3_mean": "Média de downsell nos últimos 3 meses.",
                "downsell_score": "Score de downsell.",
                "facebook_spend": "Gasto total em tráfego no Facebook.",
                "fase_atual": "Fase atual do projeto.",
                "franqueado": "Nome do franqueado.",
                "google_spend": "Gasto total em tráfego no Google",
                "id_cliente": "Identificador único do cliente.",
                "id_franqueado": "Identificador único do franqueado.",
                "id_projeto": "Identificador único do projeto.",
                "investimento": "Valor total investido.",
                "investimento_m_0_3_mean": "Média de investimento nos últimos 3 meses.",
                "investment_score": "Score de investimento.",
                "is_churn": "Indicador se o cliente está em churn (1 para sim, 0 para não).",
                "lifetime_months": "Tempo de vida do cliente em meses.",
                "margem_contribuicao": "Margem de contribuição do cliente.",
                "mhs": "MHS do cliente.",
                "mhs_m_0_3_mean": "Média de MHS nos últimos 3 meses.",
                "mhs_score": "Score de MHS.",
                "nps": "NPS do cliente.",
                "nps_m_0_3_mean": "Média de NPS nos últimos 3 meses.",
                "nps_score": "Score de NPS.",
                "observation_period": "Período de observação dos dados.",
                "ratio_receita_custo": "Razão entre receita e custo.",
                "receita": "Receita total do cliente.",
                "receita_custo_score": "Score de receita/custo.",
                "roas": "ROAS do cliente.",
                "roas_m_0_3_mean": "Média de ROAS nos últimos 3 meses.",
                "roas_score": "Score de ROAS.",
                "roi": "ROI do cliente.",
                "upsell": "Valor de upsell realizado.",
                "vlr_corretagem": "Valor de corretagem.",
                "vlr_deal": "Valor do deal.",
                "vlr_deal_atual": "Valor atual do deal.",
                "vlr_downsell": "Valor de downsell.",
                "vlr_revenue_share": "Valor de revenue share.",
                "vlr_servico_extra": "Valor de serviço extra.",
                "vlr_upsell": "Valor de upsell.",
                "escopo_projeto": "Escopo do projeto.",
                "inserted_at": "Data e hora em que os dados foram inseridos."
            }
        }
    }
